### ISSUE TITLE
Increase language support for Spanish. 

### ISSUE THREAD

**Issue by mookman288** [mookman288/crisis.js#11] opened 2016-10-22 19:02 UTC
crisis.js needs to be expanded beyond `src/langs/en.js`. The `src/templates/template.jst` file can be used for contribution. The `development` branch can be used as a starting point. 
- The `gulpfile.js` will need to be updated for the language ('es')
- A new `es.js` in `src/langs` will need to be created matching the spirit of the application to the language.
- A new `index.es.html` will need to be created that explains the application and shows it off with examples.
- A new `README.ES.MD` will need to be created. 
- Please use global neutral resources for now. 

Please make your PRs to the development branch.

**Comment by MNXANL** [comment] 2016-10-30 12:01
I can help you transating everything to spanish :)

**Comment by mookman288** [comment] 2016-10-30 17:27
That would be wonderful! Feel free to contribute.

**Comment by zenware** [comment] 2017-09-28 13:26
@mookman288 Could you explain a bit more about the English format you already have? I think I kind of get it. But I'm not sure, can "primary" and "secondary" words be followed by any "combinations"? And if so, why is it like that versus something else?

I just found [this project](https://github.com/thisandagain/sentiment) which does sentiment analysis based on some research derived wordlist. It tries to determine positive or negative sentiment in a string of text. That is to say, it tries to determine if the feeling of a sentence is basically "happy" or"sad". I guess I'm curious if you've considered combining something like that with a more specific keyword search to help minimize false positives? (Note: I'm not sure that minimizing false positives is a good thing in this case if it causes false negatives to occur)

**Comment by mookman288** [comment] 2017-09-28 15:32
Hi @zenware, 

I'm not sure if this discussion is appropriate for this particular issue because it doesn't have to do with the Spanish language translation, but I will answer your questions. If this gets any bigger we should move this to a new issue and we can continue the discussion there. 

If you haven't tried the software yet on the gh-pages version, I'd recommend doing so. The combination system that I devised is designed to provide a relatively small footprint when it comes to checking for particular combinations of words and word fragments. That is to say, I didn't want to write out all of the various word combinations I was detecting for, but I wanted those explicit combinations to be detected. Enter regular expressions. 

No, I haven't looked at integrating a project like the one you've linked, but that isn't to say it isn't a worthwhile idea. I've thought about various methods to analyze the wording of people's input. 

The difficulty I see is a combination of two concerns: 

1. I worry that we will see a greater number of triggers if we try and rank the severity of someones thoughts. Instead, it's my goal in this regard, only to rank the type of combination of words, rather than how severe those combinations may be. This is a nuanced difference. It is my poor and crude understanding that approaching an individual at the wrong time when they are in the midst of crisis would only push them away, essentially marking this software as nagware. This software should hopefully never be seen as a nag, but instead an attempt to provide comfort or support. 

2. I want to keep the footprint as small as possible so it is adoptable when and if it ever becomes ready. Right now I already dislike that the English variant is >8kb, but I am not technically apt yet at writing the most performant code. I would like to avoid using AJAX wherever possible, because it is not my intention to ever let the thoughts and feelings someone expresses to leave the safety of their viewport. I'm starting to think at some point if this grows to be bigger than it is, we would need some type of on demand neural net to process analysis of phrases, which goes against that tenet.

**Comment by zenware** [comment] 2017-10-01 22:24
Ah interesting, actually I was hoping both of my questions related to language support. (While perhaps not specifically Spanish)

As I was trying to understand just exactly how the English file was encoded so I could understand how to encode a Spanish file, which you have somewhat helped with. And then as far as sentiment analysis goes, that type of tool likely differs per-language as well.

One thing I guess I also didn't realize is that you mean for this to be entirely client-side with minimal if not no server communication whatsoever.

Something that will make Spanish difficult to add is that the "prefixes" and "suffixes" don't really work the same way at all as in English, as the words are gendered, the conjugations depend heavily on tense and person, _and_ there are fourteen tenses. See [this poster on wikipedia](https://en.wikipedia.org/wiki/Grammatical_conjugation#/media/File:Conjugaci%C3%B3n_de_correr.png) for an example of just a single verb 'run'. Compare to English where the options are 'run', 'ran', 'running'.

Since it seems like, from the [en.js file](https://github.com/mookman288/crisis.js/blob/master/src/langs/en.js), that you're basing the detection largely on 'primary' and 'endings', creating even a Spanish duplicate of your English template is very difficult.

**Comment by mookman288** [comment] 2017-10-11 04:35
@zenware my apologies for the delay in response. Admittedly, I do not know enough about other languages, and so I apologize if this is an unrealistic issue. Thank you for letting me know. If you can think of a better way to integrate other languages like Spanish, I would be very interested.

**Closed as completed** 2018-09-20 14:39 UTC
Labels: enhancement, help wanted, hacktoberfest
